// Generated by CoffeeScript 1.6.3
(function() {
  var CatchAllMessage, EnterMessage, LeaveMessage, Message, TextMessage, TopicMessage, _ref, _ref1, _ref2,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Message = (function() {
    function Message(user, done) {
      this.user = user;
      this.done = done != null ? done : false;
      this.room = this.user.room;
    }

    Message.prototype.finish = function() {
      return this.done = true;
    };

    return Message;

  })();

  TextMessage = (function(_super) {
    __extends(TextMessage, _super);

    function TextMessage(user, text, id) {
      this.user = user;
      this.text = text;
      this.id = id;
      TextMessage.__super__.constructor.call(this, this.user);
    }

    TextMessage.prototype.match = function(regex) {
      return this.text.match(regex);
    };

    TextMessage.prototype.toString = function() {
      return this.text;
    };

    return TextMessage;

  })(Message);

  EnterMessage = (function(_super) {
    __extends(EnterMessage, _super);

    function EnterMessage() {
      _ref = EnterMessage.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    return EnterMessage;

  })(Message);

  LeaveMessage = (function(_super) {
    __extends(LeaveMessage, _super);

    function LeaveMessage() {
      _ref1 = LeaveMessage.__super__.constructor.apply(this, arguments);
      return _ref1;
    }

    return LeaveMessage;

  })(Message);

  TopicMessage = (function(_super) {
    __extends(TopicMessage, _super);

    function TopicMessage() {
      _ref2 = TopicMessage.__super__.constructor.apply(this, arguments);
      return _ref2;
    }

    return TopicMessage;

  })(TextMessage);

  CatchAllMessage = (function(_super) {
    __extends(CatchAllMessage, _super);

    function CatchAllMessage(message) {
      this.message = message;
      CatchAllMessage.__super__.constructor.call(this, this.message.user);
    }

    return CatchAllMessage;

  })(Message);

  module.exports = {
    Message: Message,
    TextMessage: TextMessage,
    EnterMessage: EnterMessage,
    LeaveMessage: LeaveMessage,
    TopicMessage: TopicMessage,
    CatchAllMessage: CatchAllMessage
  };

}).call(this);
