// Generated by CoffeeScript 1.6.3
(function() {
  var Response,
    __slice = [].slice;

  Response = (function() {
    function Response(robot, message, match) {
      this.robot = robot;
      this.message = message;
      this.match = match;
      this.envelope = {
        room: this.message.room,
        user: this.message.user,
        message: this.message
      };
    }

    Response.prototype.send = function() {
      var strings, _ref;
      strings = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      return (_ref = this.robot.adapter).send.apply(_ref, [this.envelope].concat(__slice.call(strings)));
    };

    Response.prototype.emote = function() {
      var strings, _ref;
      strings = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      return (_ref = this.robot.adapter).emote.apply(_ref, [this.envelope].concat(__slice.call(strings)));
    };

    Response.prototype.reply = function() {
      var strings, _ref;
      strings = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      return (_ref = this.robot.adapter).reply.apply(_ref, [this.envelope].concat(__slice.call(strings)));
    };

    Response.prototype.topic = function() {
      var strings, _ref;
      strings = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      return (_ref = this.robot.adapter).topic.apply(_ref, [this.envelope].concat(__slice.call(strings)));
    };

    Response.prototype.play = function() {
      var strings, _ref;
      strings = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      return (_ref = this.robot.adapter).play.apply(_ref, [this.envelope].concat(__slice.call(strings)));
    };

    Response.prototype.locked = function() {
      var strings, _ref;
      strings = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      return (_ref = this.robot.adapter).locked.apply(_ref, [this.envelope].concat(__slice.call(strings)));
    };

    Response.prototype.random = function(items) {
      return items[Math.floor(Math.random() * items.length)];
    };

    Response.prototype.finish = function() {
      return this.message.finish();
    };

    Response.prototype.http = function(url, options) {
      return this.robot.http(url, options);
    };

    return Response;

  })();

  module.exports = Response;

}).call(this);
